package effects

import (
	"bytes"
	"encoding/binary"
	"io"
	"math"
	"runtime"
	"testing"
)

// sineSource generates a stereo L16 PCM sine wave at the given frequency and
// sample rate. Both channels get the same signal. Returns a ReadSeeker over
// the generated bytes.
func sineSource(freq float64, sampleRate int, durationSamples int) io.ReadSeeker {
	buf := make([]byte, durationSamples*4) // 4 bytes per stereo frame
	for i := 0; i < durationSamples; i++ {
		t := float64(i) / float64(sampleRate)
		val := math.Sin(2.0 * math.Pi * freq * t)
		sample := int16(val * math.MaxInt16 * 0.9)
		binary.LittleEndian.PutUint16(buf[i*4:], uint16(sample))
		binary.LittleEndian.PutUint16(buf[i*4+2:], uint16(sample))
	}
	return bytes.NewReader(buf)
}

// silenceSource returns a ReadSeeker of the given number of silent stereo frames.
func silenceSource(durationSamples int) io.ReadSeeker {
	buf := make([]byte, durationSamples*4)
	return bytes.NewReader(buf)
}

// rampWrap is the modulus of rampSource values. Half a wrap period is far
// larger than any alignment search deviation, so mod-nearest unwrapping of
// decoded values recovers absolute source frame indices.
const rampWrap = 16384

// rampSource generates stereo frames whose sample value is the frame index
// modulo rampWrap, making the source position decodable from output samples.
func rampSource(durationFrames int) io.ReadSeeker {
	buf := make([]byte, durationFrames*4)
	for i := 0; i < durationFrames; i++ {
		v := int16(i % rampWrap)
		binary.LittleEndian.PutUint16(buf[i*4:], uint16(v))
		binary.LittleEndian.PutUint16(buf[i*4+2:], uint16(v))
	}
	return bytes.NewReader(buf)
}

// readAll reads from r until EOF, returning the accumulated bytes.
func readAll(r io.Reader, bufSize int) ([]byte, error) {
	var result []byte
	buf := make([]byte, bufSize)
	for {
		n, err := r.Read(buf)
		if n > 0 {
			result = append(result, buf[:n]...)
		}
		if err == io.EOF {
			break
		}
		if err != nil {
			return result, err
		}
	}
	return result, nil
}

// leftSample decodes the left channel of stereo frame i.
func leftSample(data []byte, i int) int16 {
	return int16(binary.LittleEndian.Uint16(data[i*4:]))
}

// estimateFreqZC estimates the dominant frequency of the left channel from
// zero crossings, skipping the first skipFrames frames.
func estimateFreqZC(data []byte, sampleRate, skipFrames int) float64 {
	totalFrames := len(data) / 4
	if totalFrames <= skipFrames+1 {
		return 0
	}
	crossings := 0
	prev := leftSample(data, skipFrames)
	for i := skipFrames + 1; i < totalFrames; i++ {
		s := leftSample(data, i)
		if (prev >= 0 && s < 0) || (prev < 0 && s >= 0) {
			crossings++
		}
		prev = s
	}
	dur := float64(totalFrames-skipFrames) / float64(sampleRate)
	return float64(crossings) / (2.0 * dur)
}

// maxAdjacentStep returns the largest absolute left-channel sample-to-sample
// step in frames [fromFrame, toFrame).
func maxAdjacentStep(data []byte, fromFrame, toFrame int) int {
	totalFrames := len(data) / 4
	if toFrame > totalFrames {
		toFrame = totalFrames
	}
	maxStep := 0
	for i := fromFrame + 1; i < toFrame; i++ {
		d := int(leftSample(data, i)) - int(leftSample(data, i-1))
		if d < 0 {
			d = -d
		}
		if d > maxStep {
			maxStep = d
		}
	}
	return maxStep
}

// sineMaxSlope returns the theoretical max sample-to-sample step of the
// sineSource waveform (amplitude 0.9 * MaxInt16) at the given frequency.
func sineMaxSlope(freq float64, sampleRate int) float64 {
	return 0.9 * math.MaxInt16 * 2.0 * math.Pi * freq / float64(sampleRate)
}

func TestTimeStretch_PassthroughAt1x(t *testing.T) {
	const sampleRate = 44100
	const duration = 4410 // 0.1 seconds

	src := sineSource(440, sampleRate, duration)

	// Read the raw source data
	rawData, err := readAll(src, 4096)
	if err != nil {
		t.Fatal(err)
	}

	// Reset source
	src.Seek(0, io.SeekStart)

	// Read through TimeStretch at speed 1.0
	ts := NewTimeStretch().SetSource(src).SetSpeed(1.0)
	tsData, err := readAll(ts, 4096)
	if err != nil {
		t.Fatal(err)
	}

	if len(tsData) != len(rawData) {
		t.Fatalf("passthrough length mismatch: got %d, want %d", len(tsData), len(rawData))
	}

	if !bytes.Equal(tsData, rawData) {
		t.Error("passthrough output does not match source at speed 1.0")
	}
}

func TestTimeStretch_PassthroughWhenInactive(t *testing.T) {
	const sampleRate = 44100
	const duration = 4410

	src := sineSource(440, sampleRate, duration)

	rawData, err := readAll(src, 4096)
	if err != nil {
		t.Fatal(err)
	}

	src.Seek(0, io.SeekStart)

	// Set speed != 1.0 but inactive — should passthrough
	ts := NewTimeStretch().SetSource(src).SetSpeed(0.5).SetActive(false)
	tsData, err := readAll(ts, 4096)
	if err != nil {
		t.Fatal(err)
	}

	if !bytes.Equal(tsData, rawData) {
		t.Error("inactive TimeStretch should pass through source data unchanged")
	}
}

func TestTimeStretch_DurationScaling_SlowDown(t *testing.T) {
	const sampleRate = 44100
	const duration = 44100 // 1 second

	src := sineSource(440, sampleRate, duration)
	sourceBytes := duration * 4

	ts := NewTimeStretch().SetSource(src).SetSpeed(0.5)
	tsData, err := readAll(ts, 4096)
	if err != nil {
		t.Fatal(err)
	}

	// At 0.5x speed, output should be approximately 2x the source length.
	// Slack: 3% plus one max-length sequence (the EOF tail is emitted
	// verbatim rather than stretched).
	expectedLen := sourceBytes * 2
	seqMaxBytes := ts.msToFrames(ts.seqMaxMS) * 4
	tolerance := float64(expectedLen)*0.03 + float64(seqMaxBytes)

	diff := math.Abs(float64(len(tsData)) - float64(expectedLen))
	if diff > tolerance {
		t.Errorf("0.5x speed: expected ~%d bytes (±%.0f), got %d bytes (diff=%.0f)",
			expectedLen, tolerance, len(tsData), diff)
	}
}

func TestTimeStretch_DurationScaling_SpeedUp(t *testing.T) {
	const sampleRate = 44100
	const duration = 44100 // 1 second

	src := sineSource(440, sampleRate, duration)
	sourceBytes := duration * 4

	ts := NewTimeStretch().SetSource(src).SetSpeed(2.0)
	tsData, err := readAll(ts, 4096)
	if err != nil {
		t.Fatal(err)
	}

	// At 2.0x speed, output should be approximately 0.5x the source length
	expectedLen := sourceBytes / 2
	seqMaxBytes := ts.msToFrames(ts.seqMaxMS) * 4
	tolerance := float64(expectedLen)*0.03 + float64(seqMaxBytes)

	diff := math.Abs(float64(len(tsData)) - float64(expectedLen))
	if diff > tolerance {
		t.Errorf("2.0x speed: expected ~%d bytes (±%.0f), got %d bytes (diff=%.0f)",
			expectedLen, tolerance, len(tsData), diff)
	}
}

func TestTimeStretch_LengthRatio_AllSpeeds(t *testing.T) {
	const sampleRate = 48000
	const duration = 5 * sampleRate // 5 seconds

	for _, speed := range []float64{0.5, 0.75, 0.95, 1.25, 1.5, 2.0} {
		src := sineSource(330, sampleRate, duration)
		ts := NewTimeStretch().SetSource(src).SetSampleRate(sampleRate).SetQuality(QualityHigh).SetSpeed(speed)

		tsData, err := readAll(ts, 8192)
		if err != nil {
			t.Fatalf("speed %.2f: %v", speed, err)
		}

		expectedLen := float64(duration*4) / speed
		seqMaxBytes := float64(ts.msToFrames(ts.seqMaxMS) * 4)
		tolerance := expectedLen*0.02 + seqMaxBytes

		diff := math.Abs(float64(len(tsData)) - expectedLen)
		if diff > tolerance {
			t.Errorf("speed %.2f: expected ~%.0f bytes (±%.0f), got %d (diff=%.0f)",
				speed, expectedLen, tolerance, len(tsData), diff)
		}
	}
}

func TestTimeStretch_PitchPreservation(t *testing.T) {
	const sampleRate = 44100
	const duration = 88200 // 2 seconds for good frequency resolution
	const freq = 440.0

	src := sineSource(freq, sampleRate, duration)

	ts := NewTimeStretch().SetSource(src).SetSpeed(0.75).SetQuality(QualityHigh)
	tsData, err := readAll(ts, 4096)
	if err != nil {
		t.Fatal(err)
	}

	if len(tsData) < 8 {
		t.Fatal("output too short for frequency analysis")
	}

	estimatedFreq := estimateFreqZC(tsData, sampleRate, sampleRate/10)

	freqTolerance := freq * 0.02
	if math.Abs(estimatedFreq-freq) > freqTolerance {
		t.Errorf("pitch not preserved: expected ~%.0fHz (±%.1f), estimated %.1fHz",
			freq, freqTolerance, estimatedFreq)
	}
}

func TestTimeStretch_PitchPreserved_HalfAndOneAndAHalf(t *testing.T) {
	const sampleRate = 48000
	const duration = 3 * sampleRate
	const freq = 440.0

	for _, speed := range []float64{0.5, 1.5} {
		src := sineSource(freq, sampleRate, duration)
		ts := NewTimeStretch().SetSource(src).SetSampleRate(sampleRate).SetQuality(QualityHigh).SetSpeed(speed)

		tsData, err := readAll(ts, 8192)
		if err != nil {
			t.Fatalf("speed %.2f: %v", speed, err)
		}

		estimatedFreq := estimateFreqZC(tsData, sampleRate, sampleRate/10)
		if math.Abs(estimatedFreq-freq) > freq*0.01 {
			t.Errorf("speed %.2f: pitch not preserved: expected ~%.0fHz (±%.1f), estimated %.1fHz",
				speed, freq, freq*0.01, estimatedFreq)
		}
	}
}

func TestTimeStretch_NoDiscontinuities(t *testing.T) {
	const sampleRate = 48000
	const duration = 2 * sampleRate
	const freq = 220.0

	src := sineSource(freq, sampleRate, duration)
	ts := NewTimeStretch().SetSource(src).SetSampleRate(sampleRate).SetQuality(QualityHigh).SetSpeed(0.75)

	tsData, err := readAll(ts, 8192)
	if err != nil {
		t.Fatal(err)
	}

	totalFrames := len(tsData) / 4
	// Skip the fade-in at the start and the hard stop at the very end.
	from := sampleRate / 10
	to := totalFrames - 2*ts.overlap

	threshold := int(1.5 * sineMaxSlope(freq, sampleRate))
	if step := maxAdjacentStep(tsData, from, to); step > threshold {
		t.Errorf("discontinuity detected: max adjacent step %d exceeds threshold %d", step, threshold)
	}
}

func TestTimeStretch_NoDriftAt095_60s(t *testing.T) {
	const sampleRate = 48000
	const duration = 60 * sampleRate
	const speed = 0.95

	src := sineSource(440, sampleRate, duration)
	ts := NewTimeStretch().SetSource(src).SetSampleRate(sampleRate).SetQuality(QualityHigh).SetSpeed(speed)

	tsData, err := readAll(ts, 16384)
	if err != nil {
		t.Fatal(err)
	}

	// The fractional input-advance accumulator must keep the long-term tempo
	// exact: output length within one max sequence of in/speed.
	expectedFrames := float64(duration) / speed
	gotFrames := float64(len(tsData) / 4)
	slack := float64(ts.msToFrames(ts.seqMaxMS))

	if math.Abs(gotFrames-expectedFrames) > slack {
		t.Errorf("tempo drift over 60s at 0.95x: expected ~%.0f frames (±%.0f), got %.0f (diff=%.0f)",
			expectedFrames, slack, gotFrames, gotFrames-expectedFrames)
	}
}

func TestTimeStretch_SpeedChangeContinuity(t *testing.T) {
	const sampleRate = 48000
	const duration = 3 * sampleRate
	const freq = 240.0

	src := sineSource(freq, sampleRate, duration)
	ts := NewTimeStretch().SetSource(src).SetSampleRate(sampleRate).SetQuality(QualityHigh).SetSpeed(0.8)

	var out []byte
	buf := make([]byte, 8192)
	for len(out) < sampleRate*4 { // ~1s of output at 0.8x
		n, err := ts.Read(buf)
		if err != nil {
			t.Fatal(err)
		}
		out = append(out, buf[:n]...)
	}

	ts.SetSpeed(1.3)

	rest, err := readAll(ts, 8192)
	if err != nil {
		t.Fatal(err)
	}
	out = append(out, rest...)

	totalFrames := len(out) / 4
	from := sampleRate / 10
	to := totalFrames - 2*ts.overlap

	threshold := int(1.5 * sineMaxSlope(freq, sampleRate))
	if step := maxAdjacentStep(out, from, to); step > threshold {
		t.Errorf("discontinuity across speed change: max adjacent step %d exceeds threshold %d", step, threshold)
	}
}

func TestTimeStretch_UnityTransitionContinuity(t *testing.T) {
	const sampleRate = 48000

	// Part 1: sine, 0.9 → 1.0 → 1.1 — no waveform steps anywhere.
	{
		const freq = 220.0
		src := sineSource(freq, sampleRate, 3*sampleRate)
		ts := NewTimeStretch().SetSource(src).SetSampleRate(sampleRate).SetQuality(QualityHigh).SetSpeed(0.9)

		var out []byte
		buf := make([]byte, 8192)
		readFor := func(bytesWanted int) {
			for len(out) < bytesWanted {
				n, err := ts.Read(buf)
				if err == io.EOF {
					return
				}
				if err != nil {
					t.Fatal(err)
				}
				out = append(out, buf[:n]...)
			}
		}

		readFor(sampleRate / 2 * 4) // ~0.5s at 0.9x
		ts.SetSpeed(1.0)
		readFor(sampleRate * 4) // through the flush and into passthrough
		ts.SetSpeed(1.1)
		rest, err := readAll(ts, 8192)
		if err != nil {
			t.Fatal(err)
		}
		out = append(out, rest...)

		totalFrames := len(out) / 4
		threshold := int(1.5 * sineMaxSlope(freq, sampleRate))
		if step := maxAdjacentStep(out, sampleRate/10, totalFrames-2*ts.overlap); step > threshold {
			t.Errorf("discontinuity across unity transitions: max step %d exceeds threshold %d", step, threshold)
		}
	}

	// Part 2: ramp, 0.9 → 1.0 — after the flush completes, the output must be
	// consecutive source frames (verifies the seek back to the exact frame
	// following the flushed reference tail).
	{
		src := rampSource(2 * sampleRate)
		ts := NewTimeStretch().SetSource(src).SetSampleRate(sampleRate).SetQuality(QualityHigh).SetSpeed(0.9)

		var pre []byte
		buf := make([]byte, 8192)
		for len(pre) < sampleRate/2*4 {
			n, err := ts.Read(buf)
			if err != nil {
				t.Fatal(err)
			}
			pre = append(pre, buf[:n]...)
		}

		ts.SetSpeed(1.0)
		post, err := readAll(ts, 8192)
		if err != nil {
			t.Fatal(err)
		}

		postFrames := len(post) / 4
		if postFrames < rampWrap {
			t.Fatalf("not enough post-transition output: %d frames", postFrames)
		}

		// Find the longest suffix where every mod-delta is 1 (raw passthrough)
		// or 0..2 (the float-rounded reference tail).
		suffixStart := postFrames - 1
		for i := postFrames - 1; i > 0; i-- {
			d := (int(leftSample(post, i)) - int(leftSample(post, i-1)) + rampWrap) % rampWrap
			if d > 2 {
				break
			}
			suffixStart = i - 1
		}

		consecutive := postFrames - suffixStart
		if consecutive < postFrames/2 {
			t.Errorf("post-unity output not consecutive source frames: only %d of %d frames contiguous",
				consecutive, postFrames)
		}
	}
}

func TestTimeStretch_SourcePositionAccuracy(t *testing.T) {
	const sampleRate = 48000
	// Short enough that ramp values never wrap: decoded samples are absolute
	// source frame indices (crossfade blends land between their two ramps,
	// which is within the deviation bound asserted below).
	const duration = 28800 // 0.6s, < MaxInt16
	const speed = 0.5

	src := rampSource(duration)
	ts := NewTimeStretch().SetSource(src).SetSampleRate(sampleRate).SetQuality(QualityHigh).SetSpeed(speed)

	buf := make([]byte, 1920*4)
	var absPos int64
	totalOutFrames := 0

	for chunk := 0; chunk < 12; chunk++ {
		n, err := ts.Read(buf)
		if err != nil {
			t.Fatal(err)
		}
		frames := n / 4
		totalOutFrames += frames
		if frames > 0 {
			absPos = int64(leftSample(buf, frames-1))
		}

		got := ts.SourcePosition()

		// SourcePosition follows the nominal (exact-tempo) timeline: after N
		// output frames at speed s it must report N*s source frames, exactly.
		wantNominal := int64(float64(totalOutFrames) * speed * 4)
		if got < wantNominal-16 || got > wantNominal+16 {
			t.Fatalf("chunk %d: SourcePosition %d, nominal timeline %d", chunk, got, wantNominal)
		}

		// The decoded content position oscillates around the nominal timeline:
		// each sequence plays its content at 1:1 rate and the joins jump back,
		// so the deviation is bounded by (1-speed)*(seq-overlap) plus the
		// alignment search radius.
		seqFrames := ts.autoSeqFrames(speed)
		maxDev := int64((int(math.Abs(1.0-speed)*float64(seqFrames-ts.overlap)) + ts.seekRadius + ts.overlap + 8) * 4)
		wantContent := (absPos + 1) * 4
		if got < wantContent-maxDev || got > wantContent+maxDev {
			t.Fatalf("chunk %d: SourcePosition %d deviates from decoded content position %d by more than ±%d",
				chunk, got, wantContent, maxDev)
		}
	}
}

func TestTimeStretch_EOFDrainTerminates(t *testing.T) {
	const sampleRate = 48000
	const duration = sampleRate // 1 second

	src := sineSource(440, sampleRate, duration)
	ts := NewTimeStretch().SetSource(src).SetSampleRate(sampleRate).SetQuality(QualityHigh).SetSpeed(0.5)

	var total int
	buf := make([]byte, 4096)
	for i := 0; ; i++ {
		if i > 100000 {
			t.Fatal("EOF drain did not terminate within iteration cap")
		}
		n, err := ts.Read(buf)
		total += n
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatal(err)
		}
	}

	// Should have produced roughly 2x the source duration.
	if total < duration*4*3/2 {
		t.Errorf("EOF drain produced too little output: %d bytes for %d source bytes at 0.5x", total, duration*4)
	}
}

func TestTimeStretch_SeekResetsCleanly(t *testing.T) {
	const sampleRate = 48000
	const duration = 2 * sampleRate
	const speed = 0.75
	const compareBytes = sampleRate / 20 * 4 // 50ms

	read := func(ts *TimeStretch, bytesWanted int) []byte {
		var out []byte
		buf := make([]byte, 4096)
		for len(out) < bytesWanted {
			n, err := ts.Read(buf)
			if err != nil {
				t.Fatal(err)
			}
			out = append(out, buf[:n]...)
		}
		return out[:bytesWanted]
	}

	src := sineSource(330, sampleRate, duration)
	ts := NewTimeStretch().SetSource(src).SetSampleRate(sampleRate).SetQuality(QualityHigh).SetSpeed(speed)
	read(ts, sampleRate/2*4) // consume ~0.5s
	ts.Seek(0, io.SeekStart)
	afterSeek := read(ts, compareBytes)

	src2 := sineSource(330, sampleRate, duration)
	ts2 := NewTimeStretch().SetSource(src2).SetSampleRate(sampleRate).SetQuality(QualityHigh).SetSpeed(speed)
	fresh := read(ts2, compareBytes)

	if !bytes.Equal(afterSeek, fresh) {
		t.Error("output after Seek(0) does not match a fresh instance")
	}
}

func TestTimeStretch_ConcurrentSetSpeedRace(t *testing.T) {
	const sampleRate = 48000

	src := sineSource(440, sampleRate, sampleRate)
	ts := NewTimeStretch().SetSource(src).SetSampleRate(sampleRate).SetSpeed(1.25)

	done := make(chan struct{})
	go func() {
		speeds := []float64{0.75, 1.0, 1.5, 1.25}
		for i := 0; ; i++ {
			select {
			case <-done:
				return
			default:
			}
			ts.SetSpeed(speeds[i%len(speeds)])
			_ = ts.Speed()
			_ = ts.SourcePosition()
			_ = ts.OutputPosition()
			runtime.Gosched()
		}
	}()

	buf := make([]byte, 4096)
	for i := 0; i < 100000; i++ {
		_, err := ts.Read(buf)
		if err == io.EOF {
			break
		}
		if err != nil {
			close(done)
			t.Fatal(err)
		}
	}
	close(done)
}

func TestTimeStretch_QualityPresetChanges(t *testing.T) {
	ts := NewTimeStretch() // default 44100Hz

	check := func(q Quality, rate, overlapMS, seekMS int) {
		t.Helper()
		wantOverlap := overlapMS * rate / 1000
		wantSeek := seekMS * rate / 1000
		if ts.overlap != wantOverlap || ts.seekRadius != wantSeek {
			t.Errorf("quality %d @%dHz: overlap=%d seekRadius=%d, want %d/%d",
				q, rate, ts.overlap, ts.seekRadius, wantOverlap, wantSeek)
		}
		if len(ts.refStereo) != wantOverlap*2 || len(ts.refMono) != wantOverlap {
			t.Errorf("quality %d @%dHz: reference buffers not resized to overlap %d", q, rate, wantOverlap)
		}
	}

	ts.SetQuality(QualityLow)
	check(QualityLow, 44100, 6, 10)

	ts.SetQuality(QualityMedium)
	check(QualityMedium, 44100, 8, 12)

	ts.SetQuality(QualityHigh)
	check(QualityHigh, 44100, 12, 14)

	ts.SetSampleRate(48000)
	check(QualityHigh, 48000, 12, 14)
	if ts.SampleRate() != 48000 {
		t.Errorf("SampleRate: got %d, want 48000", ts.SampleRate())
	}
}

func TestTimeStretch_SeekResetsState(t *testing.T) {
	const sampleRate = 44100
	const duration = 44100

	src := sineSource(440, sampleRate, duration)

	ts := NewTimeStretch().SetSource(src).SetSpeed(0.75)

	// Read some data
	buf := make([]byte, 8192)
	ts.Read(buf)
	ts.Read(buf)

	// Seek back to start
	ts.Seek(0, io.SeekStart)

	// Verify internal state is reset
	if ts.inFrames != 0 {
		t.Errorf("inFrames not reset after Seek: %d", ts.inFrames)
	}
	if ts.pendingOutFrames() != 0 {
		t.Errorf("pending output not reset after Seek: %d", ts.pendingOutFrames())
	}
	if ts.sourceErr != nil {
		t.Errorf("sourceErr not reset after Seek: %v", ts.sourceErr)
	}

	// Should be able to read data again
	n, err := ts.Read(buf)
	if err != nil {
		t.Fatalf("Read after Seek failed: %v", err)
	}
	if n == 0 {
		t.Error("Read after Seek returned 0 bytes")
	}
}

func TestTimeStretch_EmptySource(t *testing.T) {
	src := bytes.NewReader([]byte{})
	ts := NewTimeStretch().SetSource(src).SetSpeed(0.5)

	buf := make([]byte, 4096)
	n, err := ts.Read(buf)

	if n != 0 {
		t.Errorf("expected 0 bytes from empty source, got %d", n)
	}
	if err != io.EOF {
		t.Errorf("expected io.EOF from empty source, got %v", err)
	}
}

func TestTimeStretch_ShortSource(t *testing.T) {
	// Source shorter than one sequence
	src := sineSource(440, 44100, 100) // 100 samples, less than any sequence size

	ts := NewTimeStretch().SetSource(src).SetSpeed(0.5)
	data, err := readAll(ts, 4096)
	if err != nil {
		t.Fatalf("unexpected error reading short source: %v", err)
	}

	// Should produce some output even from a short source
	if len(data) == 0 {
		t.Error("expected some output from short source, got 0 bytes")
	}
}

func TestTimeStretch_SpeedChangeMidStream(t *testing.T) {
	const sampleRate = 44100
	const duration = 44100

	src := sineSource(440, sampleRate, duration)
	ts := NewTimeStretch().SetSource(src).SetSpeed(0.75)

	// Read some data at 0.75x
	buf := make([]byte, 8192)
	n1, err := ts.Read(buf)
	if err != nil {
		t.Fatalf("first Read failed: %v", err)
	}
	if n1 == 0 {
		t.Fatal("first Read returned 0 bytes")
	}

	// Change speed mid-stream — should not panic
	ts.SetSpeed(1.5)

	n2, err := ts.Read(buf)
	if err != nil && err != io.EOF {
		t.Fatalf("Read after speed change failed: %v", err)
	}
	if n2 == 0 {
		t.Error("Read after speed change returned 0 bytes")
	}
}

func TestTimeStretch_NilSource(t *testing.T) {
	ts := NewTimeStretch()
	buf := make([]byte, 4096)

	n, err := ts.Read(buf)
	if n != 0 || err != io.EOF {
		t.Errorf("nil source: expected (0, EOF), got (%d, %v)", n, err)
	}
}

func TestTimeStretch_SpeedClamping(t *testing.T) {
	ts := NewTimeStretch()

	ts.SetSpeed(0.1)
	if ts.Speed() != 0.25 {
		t.Errorf("speed below minimum: got %f, want 0.25", ts.Speed())
	}

	ts.SetSpeed(5.0)
	if ts.Speed() != 4.0 {
		t.Errorf("speed above maximum: got %f, want 4.0", ts.Speed())
	}

	ts.SetSpeed(1.0)
	if ts.Speed() != 1.0 {
		t.Errorf("normal speed: got %f, want 1.0", ts.Speed())
	}
}

func TestTimeStretch_ApplyEffectIsNoop(t *testing.T) {
	ts := NewTimeStretch()

	data := []byte{0x10, 0x20, 0x30, 0x40}
	original := make([]byte, len(data))
	copy(original, data)

	ts.ApplyEffect(data, len(data))

	if !bytes.Equal(data, original) {
		t.Error("ApplyEffect modified data; it should be a no-op")
	}
}

func TestTimeStretch_CloneProducesIndependentCopy(t *testing.T) {
	ts := NewTimeStretch().SetSpeed(0.5).SetQuality(QualityHigh).SetActive(false)

	cloned := ts.Clone().(*TimeStretch)

	if cloned.Speed() != ts.Speed() {
		t.Errorf("clone speed: got %f, want %f", cloned.Speed(), ts.Speed())
	}
	if cloned.Quality() != ts.Quality() {
		t.Errorf("clone quality: got %d, want %d", cloned.Quality(), ts.Quality())
	}
	if cloned.Active() != ts.Active() {
		t.Errorf("clone active: got %v, want %v", cloned.Active(), ts.Active())
	}
	if cloned.overlap != ts.overlap || cloned.seekRadius != ts.seekRadius {
		t.Errorf("clone parameters: got %d/%d, want %d/%d",
			cloned.overlap, cloned.seekRadius, ts.overlap, ts.seekRadius)
	}

	// Changing clone should not affect original
	cloned.SetSpeed(2.0)
	if ts.Speed() == cloned.Speed() {
		t.Error("changing clone speed affected original")
	}
}

func TestTimeStretch_GettersSetters(t *testing.T) {
	ts := NewTimeStretch()

	ts.SetActive(false)
	if ts.Active() {
		t.Error("SetActive(false) did not work")
	}
	ts.SetActive(true)
	if !ts.Active() {
		t.Error("SetActive(true) did not work")
	}

	ts.SetQuality(QualityHigh)
	if ts.Quality() != QualityHigh {
		t.Errorf("Quality: got %d, want %d", ts.Quality(), QualityHigh)
	}

	ts.SetSpeed(1.5)
	if ts.Speed() != 1.5 {
		t.Errorf("Speed: got %f, want 1.5", ts.Speed())
	}
}
